kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: labels-operator
subjects:
- kind: ServiceAccount
  name: labels-operator
  namespace: "labels-operator"
roleRef:
  kind: ClusterRole
  name: labels-operator
  apiGroup: rbac.authorization.k8s.io
